/*************************************************************************
Name : Validator 
Author : Sandeep Kumar
Date : February 21th,2019
Usage : Validator pojo.
*************************************************************************/
public class Validator {
	/**
	 * Validator Name
	 */
	public String name { get; set; }
	/**
	 * Validator apex class Name
	 */
	public String className { get; set; }
}